[package]
name = "gi-ui-x11"
version = "0.1.0"
edition = "2024"

[dependencies]
gi-ui = { git = "https://github.com/NDRAEY/gi-ui", version = "0.1.0" }
x11rb = { version = "0.13.1", features = ["xinput", "xkb"] }
